### ISSUE TITLE
Definitions of driving styles

### ISSUE THREAD

**Issue by ghost** [WasabiRobby/wasab-autopilot#2]
`Config.NormalDrive = 786603 -- Normal Drive Style`

`Config.CrazyDrive = 1074528293 -- Crazy Drive Style`

What do these mean? Is there a way to customize the styles? I know in vMenu you can customize the driving styles, does the ped use turn signals, stop for lights, watch out for vehicles and pedestrians, etc. Is there a formula to determine these numbers?

**Comment by wasabirobby** [comment]
Values can be added to achieve a specific driving style.
Here are a few references that may help:
http://www.kronzky.info/fivemwiki/index.php/Driving_Styles

Never used this but just found:
https://vespura.com/fivem/drivingstyle/
